[package]
name = "bruteforce_8_var_sbox_bf_finder"
version = "0.1.0"
edition = "2021"

[dependencies]
boolean_function = { path = "../../" }
rayon = "1.10.0"
num-bigint = "0.4.6"
num-traits = "0.2.19"
num-iter = "0.1.45"